group = Group.create(rsvp_code: "1234", name: "Test Group")
AgeGroup.create(description: "Adult (12+)")
AgeGroup.create(description: "Child Under 12")
AgeGroup.create(description: "Child Under 5")
vidhi = Event.create(title: "Vidhi")
manglik_prasango = Event.create(title: "Manglik Prasango")
garba = Event.create(title: "Raas-Garba")
wedding = Event.create(title: "Wedding")
reception = Event.create(title: "Reception")
manglik_prasango.invites.create(group_id: group.id, num_invited: 1)
garba.invites.create(group_id: group.id, num_invited: 2)
wedding.invites.create(group_id: group.id, num_invited: 3)
reception.invites.create(group_id: group.id, num_invited: 4)
